# Generated by Selenium IDE

import json

import options as options

from src.PageObjectModel.Pages.Login import *
from src.TcBase import ChromeWebDriverSetup
from selenium.webdriver.chrome.options import Options

with open('../../config/config.json', 'r') as file: config = json.load(file)
chrome_profile = config['CHROME_ENV']['CHROME_USER_PROFILE'].strip()
options = Options(options.add_argument(f'--user-data-dir={chrome_profile}'))

user = 'admin@dotcms.com'
password = 'admin'


class Test_Login_Admin(ChromeWebDriverSetup):

    def testLoginAdmin(self):
        driver = self.driver
        self.driver.get(Login.get_urlLogin())
        login_page = Login(driver)
        login_page.doLogin(user, password)
        login_page.doClickBtnLogin()

